--liquibase formatted sql
--changeset Amir:4

ALTER TABLE CLAN ADD COLUMN VICTORIES BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE CLAN ADD COLUMN DEFEAT BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE CLAN ADD COLUMN PROFIT DOUBLE PRECISION DEFAULT 0 NOT NULL;

ALTER TABLE CLAN ADD COLUMN LOSS DOUBLE PRECISION DEFAULT 0 NOT NULL;

ALTER TABLE USR ADD COLUMN LOGIN VARCHAR(255) NOT NULL;

ALTER TABLE MOVIE ADD COLUMN APPRAISAL DOUBLE PRECISION NULL;