--liquibase formatted sql
--changeset Amir:3

ALTER TABLE CLAN ADD COLUMN EMBLEM BYTEA NOT NULL;

ALTER TABLE USR ADD COLUMN CLAN_ADMIN INTEGER NULL;

ALTER TABLE USR
    ADD CONSTRAINT FK_ADMIN_CLAN
        FOREIGN KEY (CLAN_ADMIN) REFERENCES CLAN(ID);